version: '2.1'
services:
  userdatabase:
    image: mysql:8.0
    ports:
      - "3308:3308"
    environment:
      MYSQL_USER: "mysql"
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE:       "spotify_retriever_dev"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
        - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "userdb"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  database:
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:
      MYSQL_USER: "mysql"
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "spotify_retriever_dev"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-audiofile-db-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-audiofile-db-data.sql
    networks:
      backend:
        aliases:
          - "audiofiledb"
          - "audiofiledatabase"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  configserver:
    image: spotify-retriever/configserver:0.0.1-SNAPSHOT
    ports:
       - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"
  audiofileservice:
    image: spotify-retriever/audiofile-service:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT:   "8071"
      DATABASESERVER_PORT: "3307"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend
volumes:
  db:
    driver: local
networks:
  backend:
    driver: bridge